name: ckan-cloud-operator
channels:
  - defaults
dependencies:
  - python>=3.7
  - psycopg2
  - pip:
    - pyyaml
    - kubernetes
    - click
    - toml
    - requests
    - dataflows>=0.0.37
    - dataflows-shell>=0.0.8
    - jupyterlab
