name: Continuous Deployment
on: [push]
jobs:
  Cluster_Providers:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install pip
        run: |
          python -m pip install --upgrade pip
